/* Style: دفء الفصل — واجهة عربية تحريرية دافئة، زمردي عميق، كحلي، نحاسي، وحركة هادئة. */
import { useMemo, useState } from "react";
import { Bell, BookOpen, CalendarDays, ChevronLeft, ClipboardList, FileText, GraduationCap, LayoutDashboard, LogIn, Menu, MoreHorizontal, Pencil, Plus, Search, Settings, ShieldCheck, Sparkles, Trash2, TrendingUp, UserRound, Users, X } from "lucide-react";
import { toast } from "sonner";

const students = [
  { id: 1, name: "ياسين محمد علي", group: "بنين", grade: "ثانية إعدادى", phone: "010 2345 6789", parent: "011 9834 1122", status: "ممتاز", paid: true, attendance: 18, absence: 1, late: 0, exam: "18 / 20", sheet: "شيت المعادلات", note: "تقدم واضح في الجبر" },
  { id: 2, name: "ملك أحمد حسن", group: "بنات", grade: "ثانية إعدادى", phone: "012 7654 3210", parent: "010 4432 1198", status: "متوسط", paid: true, attendance: 16, absence: 3, late: 1, exam: "15 / 20", sheet: "شيت المعادلات", note: "تحتاج مراجعة الكسور" },
  { id: 3, name: "عمر خالد سمير", group: "بنين", grade: "ثانية إعدادى", phone: "010 8321 4976", parent: "011 3388 4510", status: "ممتاز", paid: false, attendance: 17, absence: 2, late: 1, exam: "19 / 20", sheet: "شيت النسب", note: "متميز في الحل الذهني" },
  { id: 4, name: "سلمى وائل محمود", group: "بنات", grade: "ثانية إعدادى", phone: "012 1102 8834", parent: "010 9021 6621", status: "ضعيف", paid: false, attendance: 12, absence: 6, late: 2, exam: "11 / 20", sheet: "شيت المعادلات", note: "تواصل مع ولي الأمر" },
];

const menu = [
  { id: "overview", label: "نظرة عامة", icon: LayoutDashboard },
  { id: "classes", label: "الصفوف", icon: GraduationCap },
  { id: "students", label: "الطلاب", icon: Users },
  { id: "exams", label: "الامتحانات", icon: ClipboardList },
  { id: "worksheets", label: "الشيتات", icon: FileText },
  { id: "reports", label: "التقارير", icon: TrendingUp },
  { id: "settings", label: "الإعدادات", icon: Settings },
];

export default function Home() {
  const [entered, setEntered] = useState(false);
  const [active, setActive] = useState("overview");
  const [grade, setGrade] = useState("ثانية إعدادى");
  const [group, setGroup] = useState("الكل");
  const [selected, setSelected] = useState<typeof students[number] | null>(null);
  const [search, setSearch] = useState("");
  const [role, setRole] = useState<"admin" | "parent" | "student">("admin");

  const filtered = useMemo(() => students.filter(s => (group === "الكل" || s.group === group) && (s.grade === grade || active !== "students") && s.name.includes(search)), [group, grade, search, active]);

  if (!entered) return <Login onEnter={() => setEntered(true)} />;

  return <div className="app-shell" dir="rtl">
    <aside className="sidebar">
      <div className="brand-block"><img src="/manus-storage/al-imtiaz-mark_99680b5d.png" alt="شعار الامتياز" /><div><strong>الامتياز</strong><span>في الرياضيات</span></div></div>
      <div className="profile-mini"><div className="avatar">أ</div><div><b>أحمد عاطف الشافعى</b><small>مدير النظام</small></div><MoreHorizontal size={18}/></div>
      <nav>{menu.map(item => { const Icon = item.icon; return <button key={item.id} className={active === item.id ? "nav-item active" : "nav-item"} onClick={() => { setActive(item.id); if (item.id !== "students") setSelected(null); }}><Icon size={19}/><span>{item.label}</span>{item.id === "students" && <em>٤٨</em>}</button> })}</nav>
      <div className="sidebar-bottom"><div className="tip"><Sparkles size={18}/><div><b>ملاحظة اليوم</b><span>تابع الطلاب المتأخرين في الدفع</span></div></div><button className="logout" onClick={() => setEntered(false)}><LogIn size={18}/> تسجيل الخروج</button></div>
    </aside>

    <main className="main-content">
      <header className="topbar"><div className="breadcrumb"><span>الرئيسية</span><ChevronLeft size={15}/><b>{menu.find(m => m.id === active)?.label}</b></div><div className="top-actions"><div className="date"><CalendarDays size={17}/><span>الأحد، ١٥ أغسطس ٢٠٢٦</span></div><button className="icon-button" onClick={() => toast("لا توجد إشعارات جديدة") }><Bell size={19}/><i>3</i></button><div className="role-switch"><button className={role === "admin" ? "selected" : ""} onClick={() => setRole("admin")}>إدارة</button><button className={role === "parent" ? "selected" : ""} onClick={() => setRole("parent")}>ولي أمر</button><button className={role === "student" ? "selected" : ""} onClick={() => setRole("student")}>طالب</button></div></div></header>
      {role !== "admin" ? <Portal role={role} onBack={() => setRole("admin")} /> : <>
      {active === "overview" && <Overview onStudents={() => setActive("students")} />}
      {active === "classes" && <Classes grade={grade} setGrade={setGrade} onGroup={(g: string) => { setGroup(g); setActive("students"); }} />}
      {active === "students" && <StudentsView grade={grade} setGrade={setGrade} group={group} setGroup={setGroup} search={search} setSearch={setSearch} students={filtered} onSelect={setSelected} />}
      {active === "exams" && <Placeholder title="الامتحانات" icon={<ClipboardList/>} body="أنشئ نماذج امتحانات، حدّد الدرجات، وتابع نتائج كل صف في مكان واحد." action="إنشاء نموذج امتحان" />}
      {active === "worksheets" && <Placeholder title="الشيتات" icon={<FileText/>} body="إدارة أوراق العمل ومتابعة آخر شيت تم تسليمه لكل طالب." action="إضافة شيت جديد" />}
      {active === "reports" && <Reports />}
      {active === "settings" && <Placeholder title="الإعدادات" icon={<Settings/>} body="تحكم في بيانات المركز، الحسابات، التنبيهات وصلاحيات الدخول." action="حفظ التغييرات" />}
      </>}
    </main>
    {selected && <StudentDrawer student={selected} onClose={() => setSelected(null)} />}
  </div>;
}

function Login({ onEnter }: { onEnter: () => void }) { const [mode, setMode] = useState("admin"); return <div className="login-page" dir="rtl"><div className="login-art"><div className="art-overlay"><img src="/manus-storage/al-imtiaz-mark_99680b5d.png" alt=""/><p>كل طالب أمامك.<br/><strong>كل خطوة أوضح.</strong></p><span>إدارة تعليمية هادئة، مبنية على فهم التفاصيل.</span></div></div><div className="login-panel"><div className="login-brand"><img src="/manus-storage/al-imtiaz-mark_99680b5d.png" alt="شعار الامتياز"/><div><b>الامتياز</b><span>في الرياضيات</span><i>منصة الأستاذ أحمد عاطف الشافعى</i></div></div><div className="login-copy"><span className="eyebrow">منصة الإدارة التعليمية</span><h1>مرحباً بعودتك</h1><p>سجّل الدخول لترى كل طالب بوضوح، وتقرر خطوته التالية بثقة.</p></div><div className="login-tabs"><button className={mode === "admin" ? "active" : ""} onClick={() => setMode("admin")}>إدارة المنصة</button><button className={mode === "parent" ? "active" : ""} onClick={() => setMode("parent")}>ولي أمر / طالب</button></div><label>البريد الإلكتروني أو رقم الهاتف<input placeholder="أدخل البريد أو رقم الهاتف" /></label><label>كلمة المرور<input type="password" placeholder="أدخل كلمة المرور" /></label><div className="login-meta"><label className="check"><input type="checkbox"/> تذكرني</label><a href="#" onClick={() => toast("سيتم إرسال رابط الاستعادة")}>نسيت كلمة المرور؟</a></div><button className="primary large" onClick={onEnter}>دخول <ChevronLeft size={18}/></button><div className="login-foot"><ShieldCheck size={16}/> بياناتك التعليمية محفوظة وآمنة</div></div></div> }

function Overview({ onStudents }: { onStudents: () => void }) { return <section className="page"><div className="page-head"><div><span className="eyebrow">الأحد، ١٥ أغسطس</span><h1>صباح الخير، أستاذ أحمد <span>✦</span></h1><p>إليك ملخص سريع لما يحدث في المنصة اليوم.</p></div><button className="primary" onClick={onStudents}><Plus size={18}/> إضافة طالب</button></div><div className="stat-grid"><Stat title="إجمالي الطلاب" value="٤٨" detail="+ ٦ هذا الشهر" tone="green" icon={<Users/>}/><Stat title="نسبة الحضور" value="٩٢٪" detail="+ ٤٪ عن الأسبوع الماضي" tone="blue" icon={<CalendarDays/>}/><Stat title="الاشتراكات المدفوعة" value="٣٦" detail="من أصل ٤٨ طالب" tone="copper" icon={<ShieldCheck/>}/><Stat title="نماذج الامتحانات" value="١٢" detail="٣ تحتاج مراجعة" tone="purple" icon={<ClipboardList/>}/></div><div className="overview-grid"><div className="card chart-card"><div className="card-head"><div><h3>الحضور والغياب</h3><span>آخر ٧ أيام</span></div><button className="ghost">هذا الأسبوع <ChevronLeft size={15}/></button></div><div className="chart"><div className="chart-labels"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div className="bars">{[72,85,68,92,78,95,88].map((v,i)=><div className="bar-col" key={i}><div className="bar" style={{height: `${v}%`}}><i style={{height: `${Math.max(v-12,20)}%`}}/></div><small>{["الإث","الثلا","الأرب","الخمي","الجمع","السبت","الأحد"][i]}</small></div>)}</div></div></div><div className="card activity-card"><div className="card-head"><h3>آخر الأنشطة</h3><button className="text-button">عرض الكل</button></div>{[{icon:<UserRound/>, text:"تمت إضافة طالب جديد", name:"سيف محمود", time:"منذ ١٠ دقائق", c:"green"},{icon:<ClipboardList/>, text:"تم تصحيح امتحان", name:"الجبر — ثانية إعدادى", time:"منذ ٤٥ دقيقة", c:"blue"},{icon:<Bell/>, text:"تم إرسال إشعار إلى", name:"أولياء أمور ثالثة ثانوي", time:"منذ ساعة", c:"copper"}].map((a,i)=><div className="activity" key={i}><div className={`activity-icon ${a.c}`}>{a.icon}</div><div><b>{a.text}</b><span>{a.name}</span></div><time>{a.time}</time></div>)}</div></div><div className="quick-row"><button onClick={onStudents}><Users size={20}/><div><b>إدارة الطلاب</b><span>عرض وإضافة وتعديل الطلاب</span></div><ChevronLeft/></button><button onClick={() => toast("سيتم فتح منشئ نماذج الامتحانات") }><ClipboardList size={20}/><div><b>نموذج امتحان جديد</b><span>أنشئ نموذجاً في دقائق</span></div><ChevronLeft/></button><button onClick={() => toast("تم فتح مركز الإشعارات") }><Bell size={20}/><div><b>إرسال إشعار</b><span>للطالب أو ولي الأمر</span></div><ChevronLeft/></button></div></section> }

function Stat({ title, value, detail, tone, icon }: any) { return <div className="stat-card"><div className={`stat-icon ${tone}`}>{icon}</div><div><span>{title}</span><strong>{value}</strong><small className={tone === "green" ? "up" : ""}>{detail}</small></div></div> }

function Classes({ grade, setGrade, onGroup }: any) { const middle = ["أولى إعدادى","ثانية إعدادى","ثالثة إعدادى"]; const high = ["أولى ثانوى","ثانية ثانوى","ثالثة ثانوى رياضيات","ثالثة ثانوى إحصاء"]; return <section className="page"><div className="page-head"><div><span className="eyebrow">هيكل الصفوف</span><h1>الصفوف الدراسية</h1><p>اختر المرحلة والصف للوصول إلى مجموعات الطلاب.</p></div></div><div className="stage-grid"><div className="stage-card featured"><div className="stage-number">01</div><div className="stage-content"><span>المرحلة الأولى</span><h2>المرحلة الإعدادية</h2><p>٣ صفوف · ٢٨ طالب</p><div className="grade-list">{middle.map((g,i)=><button className={grade === g ? "grade active" : "grade"} key={g} onClick={() => {setGrade(g); onGroup("الكل")}}><span>{g}</span><small>{[8,11,9][i]} طلاب</small><ChevronLeft size={16}/></button>)}</div></div></div><div className="stage-card"><div className="stage-number">02</div><div className="stage-content"><span>المرحلة الثانية</span><h2>المرحلة الثانوية</h2><p>٤ صفوف · ٢٠ طالب</p><div className="grade-list">{high.map((g,i)=><button className={grade === g ? "grade active" : "grade"} key={g} onClick={() => {setGrade(g); onGroup("الكل")}}><span>{g}</span><small>{[5,4,7,4][i]} طلاب</small><ChevronLeft size={16}/></button>)}</div></div></div></div><div className="group-panel"><div><h3>اختر المجموعة</h3><p>بعد اختيار الصف، انتقل إلى مجموعة الطلاب.</p></div><div className="group-buttons"><button onClick={() => onGroup("بنين")}><span className="group-avatar blue">ب</span><b>بنين</b><small>٢٤ طالب</small><ChevronLeft/></button><button onClick={() => onGroup("بنات")}><span className="group-avatar rose">ب</span><b>بنات</b><small>٢٤ طالبة</small><ChevronLeft/></button></div></div></section> }

function StudentsView({ grade, setGrade, group, setGroup, search, setSearch, students, onSelect }: any) { return <section className="page"><div className="page-head"><div><span className="eyebrow">إدارة الطلاب</span><h1>{grade}</h1><p>تصفح بيانات الطلاب وتابع مستواهم الدراسي.</p></div><button className="primary" onClick={() => toast("نموذج إضافة طالب جاهز للتصميم") }><Plus size={18}/> إضافة طالب</button></div><div className="toolbar"><div className="search"><Search size={18}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="ابحث باسم الطالب..."/></div><div className="filter-pills">{["الكل","بنين","بنات"].map(g=><button key={g} className={group === g ? "active" : ""} onClick={() => setGroup(g)}>{g}</button>)}</div><button className="outline" onClick={() => toast("يمكنك الآن تصدير قائمة الطلاب")}>تصدير القائمة</button></div><div className="student-summary"><span>إجمالي عدد الطلاب</span><b>{students.length} <small>طالب</small></b><div className="summary-track"><i style={{width: "74%"}}/></div><span className="muted">٧٤٪ من السعة</span></div><div className="table-card"><table><thead><tr><th>اسم الطالب</th><th>المجموعة</th><th>الحضور</th><th>الحالة</th><th>الاشتراك</th><th>آخر امتحان</th><th></th></tr></thead><tbody>{students.map((s: any) => <tr key={s.id} onClick={() => onSelect(s)}><td><div className="student-name"><span className={`student-avatar ${s.group === "بنات" ? "rose" : "blue"}`}>{s.name[0]}</span><div><b>{s.name}</b><small>{s.phone}</small></div></div></td><td><span className="group-tag">{s.group}</span></td><td><div className="attendance"><b>{Math.round(s.attendance/(s.attendance+s.absence)*100)}%</b><span><i style={{width:`${Math.round(s.attendance/(s.attendance+s.absence)*100)}%`}}/></span></div></td><td><span className={`status ${s.status === "ممتاز" ? "excellent" : s.status === "متوسط" ? "average" : "weak"}`}>{s.status}</span></td><td><span className={s.paid ? "paid" : "unpaid"}>{s.paid ? "دفع" : "لم يدفع"}</span></td><td><b className="exam-score">{s.exam}</b></td><td><button className="row-more" onClick={e => { e.stopPropagation(); toast("اختر الطالب لفتح البطاقة")}}><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></div></section> }

function StudentDrawer({ student, onClose }: any) { return <div className="drawer-backdrop" onClick={onClose}><aside className="student-drawer" onClick={e => e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">بطاقة الطالب</span><h2>الملف التعليمي</h2></div><button className="icon-button" onClick={onClose}><X size={19}/></button></div><div className="drawer-profile"><span className={`big-avatar ${student.group === "بنات" ? "rose" : "blue"}`}>{student.name[0]}</span><div><h3>{student.name}</h3><span>{student.grade} · {student.group}</span></div><span className={`status ${student.status === "ممتاز" ? "excellent" : student.status === "متوسط" ? "average" : "weak"}`}>{student.status}</span></div><div className="drawer-actions"><button className="primary" onClick={() => toast("تم فتح وضع التعديل")}><Pencil size={16}/> تعديل</button><button className="danger" onClick={() => toast("يتطلب حذف الطالب تأكيداً") }><Trash2 size={16}/> حذف</button></div><div className="detail-section"><h4>البيانات الأساسية</h4><div className="details-grid"><Detail label="رقم الهاتف" value={student.phone}/><Detail label="رقم ولي الأمر" value={student.parent}/><Detail label="الصف" value={student.grade}/><Detail label="الاشتراك" value={student.paid ? "تم الدفع" : "لم يتم الدفع"}/></div></div><div className="detail-section"><h4>المتابعة الدراسية</h4><div className="metric-row"><Metric label="الحضور" value={student.attendance} tone="green"/><Metric label="الغياب" value={student.absence} tone="rose"/><Metric label="التأخير" value={student.late} tone="copper"/></div><div className="last-items"><div><span>آخر امتحان</span><b>{student.exam}</b></div><div><span>آخر شيت</span><b>{student.sheet}</b></div></div></div><div className="detail-section note"><h4>الملاحظات</h4><p>{student.note}</p></div><button className="notify-button" onClick={() => toast("تم تجهيز رسالة الإشعار") }><Bell size={17}/> إرسال إشعار للطالب</button><button className="notify-button secondary" onClick={() => toast("تم تجهيز رسالة ولي الأمر") }><Users size={17}/> إرسال إشعار لولي الأمر</button></aside></div> }
const Detail = ({label,value}: any) => <div><span>{label}</span><b>{value}</b></div>; const Metric = ({label,value,tone}: any) => <div className="metric"><span className={`metric-icon ${tone}`}>{value}</span><div><b>{label}</b><small>هذا الشهر</small></div></div>;
function Reports() { return <section className="page"><div className="page-head"><div><span className="eyebrow">قراءة الأداء</span><h1>التقارير والمتابعة</h1><p>صورة مختصرة عن تقدم الطلاب والصفوف.</p></div><button className="outline">تحميل التقرير</button></div><div className="report-banner"><div><span>مؤشر الأداء العام</span><strong>٨٦٪</strong><p>تحسن ملحوظ مقارنة بالشهر الماضي</p></div><div className="ring"><b>٨٦</b><span>٪</span></div></div><div className="report-grid"><div className="card"><div className="card-head"><h3>الأداء حسب المرحلة</h3><MoreHorizontal size={18}/></div>{[{name:"المرحلة الإعدادية",v:92,c:"green"},{name:"المرحلة الثانوية",v:78,c:"blue"},{name:"ثالثة ثانوى إحصاء",v:68,c:"copper"}].map(x=><div className="progress-row" key={x.name}><div><b>{x.name}</b><span>{x.v}%</span></div><span className="progress"><i className={x.c} style={{width:`${x.v}%`}}/></span></div>)}</div><Placeholder title="نماذج الامتحانات" icon={<BookOpen/>} body="أنشئ نماذج امتحانات جديدة وقارن النتائج." action="إدارة النماذج"/></div></section> }
function Placeholder({title,icon,body,action}: any) { return <section className="page"><div className="page-head"><div><span className="eyebrow">مركز الأدوات</span><h1>{title}</h1><p>{body}</p></div><button className="primary" onClick={() => toast("تم فتح مساحة التصميم") }><Plus size={18}/>{action}</button></div><div className="empty-state"><div className="empty-icon">{icon}</div><h2>مساحة {title} جاهزة</h2><p>هذه الشاشة مصممة لتكون نقطة البداية لإدارة {title} بشكل واضح ومنظم.</p><button className="outline" onClick={() => toast("سيتم إضافة البيانات من هنا")}>ابدأ الآن <ChevronLeft size={16}/></button></div></section> }
function Portal({ role, onBack }: any) { const isParent = role === "parent"; return <section className="page portal"><button className="back-link" onClick={onBack}><ChevronLeft size={16}/> العودة إلى لوحة الإدارة</button><div className="portal-hero"><div><span className="eyebrow">{isParent ? "بوابة ولي الأمر" : "بوابة الطالب"}</span><h1>{isParent ? "تابع رحلة ابنك التعليمية" : "بياناتك وتقاريرك في مكان واحد"}</h1><p>{isParent ? "اطّلع على الحضور والاشتراك ونتائج الامتحانات أولاً بأول." : "راجع مستواك، إنجازاتك، وآخر المهام المطلوبة منك."}</p></div><div className="portal-mark"><GraduationCap size={48}/></div></div><div className="portal-grid"><div className="card portal-student"><span className="student-avatar blue">ي</span><div><span>الطالب</span><h2>ياسين محمد علي</h2><p>ثانية إعدادى · بنين</p></div><span className="status excellent">ممتاز</span></div><div className="card"><div className="card-head"><h3>ملخص الأداء</h3><TrendingUp size={18}/></div><div className="portal-metrics"><div><b>٩٢٪</b><span>الحضور</span></div><div><b>١٨/٢٠</b><span>آخر امتحان</span></div><div><b>٨٦٪</b><span>المتوسط العام</span></div></div></div><div className="card"><div className="card-head"><h3>آخر التقارير</h3><FileText size={18}/></div><div className="report-line"><span>تقرير شهر أغسطس</span><small>جاهز للعرض</small><ChevronLeft size={16}/></div><div className="report-line"><span>نتيجة امتحان الجبر</span><small>منذ يومين</small><ChevronLeft size={16}/></div></div></div></section> }
