import { useEffect, useMemo, useRef, useState } from "react";
import { Bell, BookOpen, CalendarCheck, ClipboardList, CreditCard, FileText, LogOut, RefreshCw, ShieldCheck, Users } from "lucide-react";
import { toast } from "sonner";
import * as QRCode from "qrcode";
import QrScanner from "qr-scanner";
import { ApiError, laravelApi, type Attendance, type ExamResult, type Payment, type Role, type Student, type Worksheet } from "@/lib/laravelApi";

type Tab = "overview" | "attendance" | "exams" | "payments" | "worksheets";
const roleLabels: Record<Role, string> = { admin: "مدير النظام", teacher: "مدرس", parent: "ولي أمر", student: "طالب" };

export default function LiveDashboard() {
  const [user, setUser] = useState<Awaited<ReturnType<typeof laravelApi.me>> | null>(null);
  const [loading, setLoading] = useState(true);
  const [loginMode, setLoginMode] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { if (!laravelApi.getToken()) { setLoading(false); return; } laravelApi.me().then(setUser).catch(() => laravelApi.logout().catch(() => undefined)).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="live-loading"><RefreshCw className="spin"/> جارٍ التحقق من الحساب...</div>;
  if (!user) return <LoginPanel onSuccess={setUser} mode={loginMode} setMode={setLoginMode} error={error} setError={setError}/>;
  return <AuthenticatedDashboard user={user} onLogout={async () => { await laravelApi.logout(); setUser(null); }}/>;
}

function LoginPanel({ onSuccess, mode, setMode, error, setError }: { onSuccess: (user: Awaited<ReturnType<typeof laravelApi.me>>) => void; mode: boolean; setMode: (value: boolean) => void; error: string; setError: (value: string) => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [role, setRole] = useState<"parent" | "student">("parent"); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { const user = mode ? await laravelApi.login({ email, password }) : await laravelApi.register({ name, email, password, password_confirmation: password, role }); onSuccess(user); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "تعذر الاتصال بالخادم"); } finally { setBusy(false); } };
  return <div className="live-login" dir="rtl"><div className="live-login-card"><span className="eyebrow">بوابة الامتياز الآمنة</span><h1>{mode ? "مرحباً بعودتك" : "إنشاء حساب جديد"}</h1><p>{mode ? "سجّل الدخول للوصول إلى لوحة تناسب صلاحياتك." : "أنشئ حساب ولي أمر أو طالب للمتابعة التعليمية."}</p><form onSubmit={submit}>{!mode && <><label>الاسم<input required value={name} onChange={e => setName(e.target.value)} /></label><label>نوع الحساب<select value={role} onChange={e => setRole(e.target.value as typeof role)}><option value="parent">ولي أمر</option><option value="student">طالب</option></select></label></>}<label>البريد الإلكتروني<input type="email" required value={email} onChange={e => setEmail(e.target.value)} /></label><label>كلمة المرور<input type="password" required value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <p className="live-error">{error}</p>}<button className="primary large" disabled={busy}>{busy ? "جارٍ التنفيذ..." : mode ? "دخول" : "إنشاء الحساب"}</button></form><button className="text-button live-switch" onClick={() => setMode(!mode)}>{mode ? "إنشاء حساب جديد" : "لديك حساب؟ تسجيل الدخول"}</button></div></div>;
}

function AuthenticatedDashboard({ user, onLogout }: { user: Awaited<ReturnType<typeof laravelApi.me>>; onLogout: () => Promise<void> }) {
  const [tab, setTab] = useState<Tab>(user.role === "student" || user.role === "parent" ? "overview" : "overview");
  const [students, setStudents] = useState<Student[]>([]); const [worksheets, setWorksheets] = useState<Worksheet[]>([]); const [attendance, setAttendance] = useState<Attendance[]>([]); const [exams, setExams] = useState<ExamResult[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [busy, setBusy] = useState(true);
  const restricted = user.role === "student" || user.role === "parent";
  const load = async () => { setBusy(true); try { const [nextStudents, nextWorksheets, nextAttendance, nextExams, nextPayments] = await Promise.all([laravelApi.students(), laravelApi.worksheets(), laravelApi.attendance(), laravelApi.exams(), laravelApi.payments()]); setStudents(nextStudents); setWorksheets(nextWorksheets); setAttendance(nextAttendance); setExams(nextExams); setPayments(nextPayments); } catch (caught) { toast(caught instanceof ApiError ? caught.message : "تعذر تحميل البيانات"); } finally { setBusy(false); } };
  useEffect(() => { load(); }, []);
  const currentStudent = user.student_account?.student || students[0];
  const ownAssignments = useMemo(() => worksheets.flatMap(item => item.assignments || []).filter(item => !currentStudent || item.student?.id === currentStudent.id), [worksheets, currentStudent]);
  return <div className="live-shell" dir="rtl"><aside className="live-sidebar"><div className="brand-block"><img src="/manus-storage/al-imtiaz-mark_99680b5d.png" alt="شعار الامتياز"/><div><strong>الامتياز</strong><span>في الرياضيات</span></div></div><div className="live-user"><span className="avatar">{user.name?.[0] || "م"}</span><div><b>{user.name}</b><small>{roleLabels[user.role]}</small></div></div><nav>{(restricted ? [{id:"overview",label:"ملخصي",icon:ShieldCheck}] : [{id:"overview",label:"نظرة عامة",icon:ShieldCheck},{id:"attendance",label:"الحضور",icon:CalendarCheck},{id:"exams",label:"نتائج الامتحانات",icon:ClipboardList},{id:"payments",label:"الاشتراكات",icon:CreditCard},{id:"worksheets",label:"الشيتات",icon:FileText}]).map(item => { const Icon=item.icon; return <button key={item.id} className={tab===item.id?"live-nav active":"live-nav"} onClick={() => setTab(item.id as Tab)}><Icon size={18}/>{item.label}</button>; })}</nav><button className="live-logout" onClick={onLogout}><LogOut size={17}/> تسجيل الخروج</button></aside><main className="live-main"><header className="live-topbar"><div><span className="eyebrow">{roleLabels[user.role]}</span><h1>{restricted ? `لوحتك التعليمية، ${user.name}` : "لوحة الإدارة التعليمية"}</h1></div><button className="outline" onClick={load}><RefreshCw size={15}/> تحديث البيانات</button></header>{busy ? <div className="live-loading"><RefreshCw className="spin"/> جارٍ تحميل البيانات...</div> : restricted ? <LearnerDashboard user={user} student={currentStudent} assignments={ownAssignments} attendance={attendance} exams={exams} payments={payments}/> : <AdminView tab={tab} students={students} attendance={attendance} exams={exams} payments={payments} onRefresh={load}/>}</main></div>;
}

function LearnerDashboard({ user, student, assignments, attendance, exams, payments }: { user: Awaited<ReturnType<typeof laravelApi.me>>; student?: Student; assignments: any[]; attendance: Attendance[]; exams: ExamResult[]; payments: Payment[] }) { const present = attendance.filter(item => item.status === "present").length; return <section className="live-page"><StudentQrCard student={student}/><div className="live-hero"><div><span className="eyebrow">{user.role === "parent" ? "بوابة ولي الأمر" : "بوابة الطالب"}</span><h2>{student?.name || user.name}</h2><p>{student ? `${student.grade} · ${student.group}` : "لا يوجد ملف طالب مرتبط بعد"}</p></div><BookOpen size={48}/></div><div className="live-stats"><Stat icon={<CalendarCheck/>} label="الحضور" value={`${present}/${attendance.length || 0}`}/><Stat icon={<ClipboardList/>} label="الامتحانات" value={`${exams.length}`}/><Stat icon={<CreditCard/>} label="المدفوعات" value={`${payments.filter(item => item.status === "paid").length}`}/><Stat icon={<FileText/>} label="الشيتات" value={`${assignments.length}`}/></div><div className="live-grid"><div className="card"><div className="card-head"><h3>آخر النتائج</h3><ClipboardList size={18}/></div>{exams.slice(0,4).map(item => <div className="live-row" key={item.id}><span>{item.title}</span><b>{item.score}/{item.max_score}</b></div>)}</div><div className="card"><div className="card-head"><h3>حالة الاشتراكات</h3><CreditCard size={18}/></div>{payments.slice(0,4).map(item => <div className="live-row" key={item.id}><span>{item.due_at}</span><b className={`payment-${item.status}`}>{item.status}</b></div>)}</div></div></section>; }

function StudentQrCard({ student }: { student?: Student }) {
  const [image, setImage] = useState("");
  useEffect(() => { if (!student?.id) return; laravelApi.studentQr(student.id).then(result => QRCode.toDataURL(result.payload, { width: 180, margin: 2, color: { dark: "#123e35", light: "#fffdf8" } })).then(setImage).catch(() => setImage("")); }, [student?.id]);
  if (!student) return null;
  return <div className="card student-qr-card"><div><span className="eyebrow">رمز الحضور الشخصي</span><h3>{student.name}</h3><p>اعرض هذا الرمز عند الوصول ليتم تسجيل حضورك تلقائياً مع التاريخ والوقت.</p></div>{image ? <img src={image} alt={`رمز حضور ${student.name}`}/> : <RefreshCw className="spin"/>}</div>;
}

function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="live-stat"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></div>; }
function AdminView({ tab, students, attendance, exams, payments, onRefresh }: { tab: Tab; students: Student[]; attendance: Attendance[]; exams: ExamResult[]; payments: Payment[]; onRefresh: () => Promise<void> }) { if (tab === "attendance") return <CrudPanel title="إدارة الحضور" icon={<CalendarCheck/>} rows={attendance} fields={["student_id","date_at","status","note"]} onRefresh={onRefresh} create={laravelApi.createAttendance} update={laravelApi.updateAttendance} remove={laravelApi.deleteAttendance}/>; if (tab === "exams") return <CrudPanel title="نتائج الامتحانات" icon={<ClipboardList/>} rows={exams} fields={["student_id","title","score","max_score","taken_at"]} onRefresh={onRefresh} create={laravelApi.createExam} update={laravelApi.updateExam} remove={laravelApi.deleteExam}/>; if (tab === "payments") return <CrudPanel title="الاشتراكات والمدفوعات" icon={<CreditCard/>} rows={payments} fields={["student_id","amount","status","due_at"]} onRefresh={onRefresh} create={laravelApi.createPayment} update={laravelApi.updatePayment} remove={laravelApi.deletePayment}/>; return <section className="live-page"><QrAttendancePanel students={students} onRefresh={onRefresh}/><div className="live-hero"><div><span className="eyebrow">مركز الإدارة</span><h2>بيانات حية من Laravel</h2><p>الطلاب: {students.length} · الحضور: {attendance.length} · الامتحانات: {exams.length} · المدفوعات: {payments.length}</p></div><Users size={48}/></div><div className="live-grid"><div className="card"><div className="card-head"><h3>مؤشرات اليوم</h3><Bell size={18}/></div><div className="live-row"><span>حضور مسجل</span><b>{attendance.filter(item => item.status === "present").length}</b></div><div className="live-row"><span>مدفوعات معلقة</span><b>{payments.filter(item => item.status !== "paid").length}</b></div></div><div className="card"><div className="card-head"><h3>إجراءات سريعة</h3><ShieldCheck size={18}/></div><p className="muted">استخدم القائمة الجانبية لإدارة السجلات مباشرة من واجهة Laravel.</p></div></div></section>; }

function LiveQrScanner({ onScan }: { onScan: (payload: string) => Promise<void> }) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const scannerRef = useRef<QrScanner | null>(null);
  const onScanRef = useRef(onScan);
  const lockedRef = useRef(false);
  const [state, setState] = useState<"idle" | "starting" | "active" | "error">("idle");
  const [error, setError] = useState("");
  onScanRef.current = onScan;
  const stop = () => { scannerRef.current?.destroy(); scannerRef.current = null; lockedRef.current = false; setState("idle"); };
  const start = async () => {
    if (!videoRef.current || scannerRef.current) return;
    setState("starting"); setError("");
    try {
      if (!(await QrScanner.hasCamera())) throw new Error("لم يتم العثور على كاميرا متاحة");
      const scanner = new QrScanner(videoRef.current, async result => {
        if (lockedRef.current) return;
        lockedRef.current = true;
        try { await onScanRef.current(result.data); } finally { window.setTimeout(() => { lockedRef.current = false; }, 1200); }
      }, { preferredCamera: "environment", maxScansPerSecond: 5, highlightScanRegion: true, highlightCodeOutline: true, returnDetailedScanResult: true, onDecodeError: decodeError => { if (decodeError !== QrScanner.NO_QR_CODE_FOUND) setError("تعذر قراءة الصورة من الكاميرا"); } });
      scannerRef.current = scanner;
      await scanner.start();
      setState("active");
    } catch (caught) {
      scannerRef.current?.destroy(); scannerRef.current = null; setState("error"); setError(caught instanceof Error ? caught.message : "تعذر تشغيل الكاميرا. تحقق من إذن الكاميرا أو استخدم الإدخال اليدوي.");
    }
  };
  useEffect(() => () => { scannerRef.current?.destroy(); scannerRef.current = null; }, []);
  return <div className="camera-scanner"><div className="camera-head"><div><b>المسح بالكاميرا</b><small>اسمح للكاميرا ثم وجّهها إلى QR الطالب</small></div><span className={`camera-status ${state}`}>{state === "active" ? "مباشر" : state === "starting" ? "جارٍ التشغيل" : state === "error" ? "يحتاج مراجعة" : "متوقف"}</span></div><div className="camera-frame"><video ref={videoRef} muted playsInline/></div><div className="camera-actions">{state === "active" ? <button type="button" className="outline" onClick={stop}>إيقاف الكاميرا</button> : <button type="button" className="primary" onClick={() => void start()} disabled={state === "starting"}>{state === "starting" ? "جارٍ طلب الإذن..." : "تشغيل الكاميرا"}</button>}<small>يمكنك استخدام قارئ USB أو الإدخال اليدوي أدناه كبديل.</small></div>{error && <p className="qr-result camera-error">{error}</p>}</div>;
}

function QrAttendancePanel({ students, onRefresh }: { students: Student[]; onRefresh: () => Promise<void> }) {
  const [selectedStudentId, setSelectedStudentId] = useState("");
  const [qrImage, setQrImage] = useState("");
  const [scanPayload, setScanPayload] = useState("");
  const [scanMessage, setScanMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const generate = async () => { if (!selectedStudentId) return toast("اختر طالباً أولاً"); setBusy(true); try { const result = await laravelApi.studentQr(Number(selectedStudentId)); setQrImage(await QRCode.toDataURL(result.payload, { width: 240, margin: 2, color: { dark: "#123e35", light: "#fffdf8" } })); } catch (caught) { toast(caught instanceof ApiError ? caught.message : "تعذر توليد QR"); } finally { setBusy(false); } };
  const submitPayload = async (payload: string) => { if (!payload.trim()) return; setBusy(true); setScanMessage(""); try { const result = await laravelApi.scanAttendance(payload.trim()); setScanMessage(result.already_recorded ? `تم تسجيل حضور ${result.attendance.student?.name || "الطالب"} مسبقاً اليوم.` : `تم تسجيل حضور ${result.attendance.student?.name || "الطالب"} في ${new Date(result.attendance.date_at).toLocaleTimeString("ar-EG")}.`); setScanPayload(""); await onRefresh(); } catch (caught) { setScanMessage(caught instanceof ApiError ? caught.message : "تعذر قراءة QR"); } finally { setBusy(false); } };
  const scan = async (event: React.FormEvent) => { event.preventDefault(); await submitPayload(scanPayload); };
  return <div className="card qr-panel"><div className="card-head"><div><span className="eyebrow">حضور ذكي</span><h3>بطاقة الطالب ومسح الحضور</h3></div><ShieldCheck size={19}/></div><div className="qr-layout"><div className="qr-generator"><label>عرض QR الطالب<select value={selectedStudentId} onChange={e => setSelectedStudentId(e.target.value)}><option value="">اختر طالباً</option>{students.map(student => <option key={student.id} value={student.id}>{student.name} — {student.grade}</option>)}</select></label><button className="primary" onClick={generate} disabled={busy}>توليد بطاقة QR</button>{qrImage && <div className="qr-preview"><img src={qrImage} alt="رمز حضور الطالب"/><small>يعرض الطالب هذا الرمز عند الحضور</small></div>}</div><div className="qr-scanner"><LiveQrScanner onScan={submitPayload}/><form onSubmit={scan}><label>الإدخال اليدوي أو قارئ USB<input value={scanPayload} onChange={e => setScanPayload(e.target.value)} placeholder="ألصق الرمز هنا أو استخدم قارئاً"/></label><button className="primary" disabled={busy}>تسجيل الحضور الآن</button>{scanMessage && <p className="qr-result">{scanMessage}</p>}</form><small>يُحفظ التاريخ والوقت من الخادم، ويُمنع تكرار حضور الطالب في اليوم نفسه.</small></div></div></div>;
}

function CrudPanel<T extends { id: number }>({ title, icon, rows, fields, onRefresh, create, update, remove }: { title: string; icon: React.ReactNode; rows: T[]; fields: string[]; onRefresh: () => Promise<void>; create: (payload: any) => Promise<any>; update: (id: number, payload: any) => Promise<any>; remove: (id: number) => Promise<any> }) { const [form, setForm] = useState<Record<string,string>>({}); const [editing, setEditing] = useState<number | null>(null); const [saving, setSaving] = useState(false); const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const payload={...form, student_id: Number(form.student_id), score: form.score ? Number(form.score):undefined, max_score: form.max_score ? Number(form.max_score):undefined, amount: form.amount ? Number(form.amount):undefined }; if (editing) await update(editing,payload); else await create(payload); setForm({}); setEditing(null); await onRefresh(); toast("تم حفظ السجل"); } catch (caught) { toast(caught instanceof ApiError ? caught.message : "تعذر حفظ السجل"); } finally { setSaving(false); } }; return <section className="live-page"><div className="page-head"><div><span className="eyebrow">بيانات حية</span><h2>{title}</h2></div><span className="live-count">{rows.length} سجل</span></div><form className="card live-crud-form" onSubmit={save}>{fields.map(field => <label key={field}>{field}<input required={field !== "note"} value={form[field] || ""} onChange={e => setForm({...form,[field]:e.target.value})}/></label>)}<button className="primary" disabled={saving}>{editing ? "تحديث" : "إضافة"}</button>{editing && <button type="button" className="outline" onClick={() => { setEditing(null); setForm({}); }}>إلغاء</button>}</form><div className="card table-card"><table><thead><tr>{fields.map(field => <th key={field}>{field}</th>)}<th>إجراء</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}>{fields.map(field => <td key={field}>{String((row as any)[field] ?? "—")}</td>)}<td><button className="text-button" onClick={() => { setEditing(row.id); setForm(Object.fromEntries(fields.map(field => [field,String((row as any)[field] ?? "")]))); }}>تعديل</button><button className="text-button danger-text" onClick={async () => { await remove(row.id); await onRefresh(); toast("تم حذف السجل"); }}>حذف</button></td></tr>)}</tbody></table></div></section>; }
