import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, BarChart3, Bell, BookOpen, CalendarCheck, ChevronLeft, ClipboardList, CreditCard, FileText, GraduationCap, LogOut, Package, PieChart, RefreshCw, Search, Settings, ShieldCheck, Target, TrendingUp, UserRound, Users, X } from "lucide-react";
import { toast } from "sonner";
import * as QRCode from "qrcode";
import QrScanner from "qr-scanner";
import { ApiError, laravelApi, syncOfflineQueue, type Attendance, type ExamResult, type Payment, type Role, type Student, type Worksheet } from "@/lib/laravelApi";
import { cacheDashboardSnapshot, readDashboardSnapshot } from "@/lib/offlineStore";
import PluginStorePanel from "@/components/PluginStorePanel";
import MathUniverseBackground from "@/components/MathUniverseBackground";

type Tab = "overview" | "classes" | "students" | "attendance" | "qr" | "exams" | "payments" | "worksheets" | "reports" | "plugins" | "settings";
type Portal = "admin" | "parent" | "student";
const portalLabels: Record<Portal, string> = { admin: "إدارة المركز", parent: "ولي الأمر", student: "الطالب" };
const roleLabels: Record<Role, string> = { admin: "مدير النظام", teacher: "مدرس", parent: "ولي أمر", student: "طالب" };
const fieldLabels: Record<string, string> = { student_id: "الطالب", date_at: "التاريخ والوقت", attendance_date: "تاريخ الحضور", status: "الحالة", note: "ملاحظات", title: "العنوان", score: "الدرجة", max_score: "الدرجة الكاملة", taken_at: "وقت الاختبار", amount: "المبلغ", due_at: "موعد الاستحقاق", paid_at: "تاريخ السداد", feedback: "ملاحظات المعلم", assigned_at: "تاريخ التكليف", submitted_at: "تاريخ التسليم", subject: "المادة", grade: "الصف", group: "المجموعة", phone: "هاتف الطالب", parent_phone: "هاتف ولي الأمر", name: "الاسم" };
const statusLabels: Record<string, string> = { present: "حاضر", absent: "غائب", late: "متأخر", paid: "مدفوع", pending: "معلّق", overdue: "متأخر السداد", assigned: "مكلّف", in_progress: "قيد الحل", submitted: "تم التسليم", graded: "تم التصحيح", draft: "مسودة", published: "منشور", excellent: "ممتاز", average: "متوسط", weak: "يحتاج متابعة" };
const labelForField = (field: string) => fieldLabels[field] || field.replaceAll("_", " ");
const formatHumanDate = (value: unknown, dateOnly = false) => { if (!value) return "—"; const date = new Date(String(value)); if (Number.isNaN(date.getTime())) return String(value); return new Intl.DateTimeFormat("ar-EG", dateOnly ? { year: "numeric", month: "long", day: "numeric" } : { year: "numeric", month: "long", day: "numeric", hour: "numeric", minute: "2-digit" }).format(date); };
const formatFieldValue = (field: string, value: unknown, row?: { student?: { name?: string } }) => { if (value === null || value === undefined || value === "") return "—"; if (field === "student_id" && row?.student?.name) return row.student.name; if (field === "status") return statusLabels[String(value)] || String(value); if (field.endsWith("_at")) return formatHumanDate(value); if (field.endsWith("_date")) return formatHumanDate(value, true); if (field === "amount") return `${new Intl.NumberFormat("ar-EG").format(Number(value))} جنيه`; return String(value); };

export default function LiveDashboard({ initialPortal = "admin" }: { initialPortal?: Portal }) {
  const [user, setUser] = useState<Awaited<ReturnType<typeof laravelApi.me>> | null>(null);
  const [loading, setLoading] = useState(true);
  const [loginMode, setLoginMode] = useState(true);
  const [portal, setPortal] = useState<Portal>(initialPortal);
  const [error, setError] = useState("");
  useEffect(() => { if (!laravelApi.getToken()) { setLoading(false); return; } laravelApi.me().then(setUser).catch(() => laravelApi.logout().catch(() => undefined)).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="live-loading"><MathUniverseBackground tone="auth"/><div className="live-loading__content"><RefreshCw className="spin"/> جارٍ التحقق من الحساب...</div></div>;
  if (!user) return <LoginPanel portal={portal} setPortal={setPortal} onSuccess={setUser} mode={loginMode} setMode={setLoginMode} error={error} setError={setError}/>;
  return <AuthenticatedDashboard user={user} onLogout={async () => { await laravelApi.logout(); setUser(null); }}/>;
}

function LoginPanel({ portal, setPortal, onSuccess, mode, setMode, error, setError }: { portal: Portal; setPortal: (value: Portal) => void; onSuccess: (user: Awaited<ReturnType<typeof laravelApi.me>>) => void; mode: boolean; setMode: (value: boolean) => void; error: string; setError: (value: string) => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [role, setRole] = useState<"parent" | "student">("parent"); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { const user = mode ? await laravelApi.loginAsRole(portal, { email, password }) : await laravelApi.register({ name, email, password, password_confirmation: password, role }); onSuccess(user); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "تعذر الاتصال بالخادم"); } finally { setBusy(false); } };
  return <div className="live-login" dir="rtl"><MathUniverseBackground tone="auth"/><div className="live-login-card"><div className="login-brand"><img src="/manus-storage/al-imtiaz-mark_99680b5d.png" alt="شعار الامتياز"/><div><b>الامتياز في الرياضيات</b><span>تعلم أوضح. نتائج أقوى.</span></div></div><span className="eyebrow">بوابة الامتياز الآمنة</span><h1>{portalLabels[portal]}</h1><p>{mode ? `تسجيل دخول ${portalLabels[portal]} إلى بوابة الامتياز في الرياضيات.` : "أنشئ حساب ولي أمر أو طالب للمتابعة التعليمية."}</p><div className="login-portals">{(["admin", "parent", "student"] as Portal[]).map(item => <button type="button" key={item} className={portal === item ? "login-portal active" : "login-portal"} onClick={() => { setPortal(item); setMode(true); setError(""); }}>{portalLabels[item]}</button>)}</div><form onSubmit={submit}>{!mode && portal !== "admin" && <><label>الاسم<input required value={name} onChange={e => setName(e.target.value)} /></label><label>نوع الحساب<select value={role} onChange={e => setRole(e.target.value as typeof role)}><option value="parent">ولي أمر</option><option value="student">طالب</option></select></label></>}<label>البريد الإلكتروني<input type="email" required value={email} onChange={e => setEmail(e.target.value)} /></label><label>كلمة المرور<input type="password" required value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <p className="live-error">{error}</p>}<button className="primary large" disabled={busy}>{busy ? "جارٍ التنفيذ..." : "دخول"}</button></form>{portal !== "admin" && <button className="text-button live-switch" onClick={() => setMode(!mode)}>{mode ? "إنشاء حساب جديد" : "لديك حساب؟ تسجيل الدخول"}</button>}<small className="login-note">دخول الإدارة منفصل ومخصص للعاملين بالمركز.</small></div></div>;
}

function AuthenticatedDashboard({ user, onLogout }: { user: Awaited<ReturnType<typeof laravelApi.me>>; onLogout: () => Promise<void> }) {
  const [tab, setTab] = useState<Tab>(user.role === "student" || user.role === "parent" ? "overview" : "overview");
  const [students, setStudents] = useState<Student[]>([]); const [worksheets, setWorksheets] = useState<Worksheet[]>([]); const [attendance, setAttendance] = useState<Attendance[]>([]); const [exams, setExams] = useState<ExamResult[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [busy, setBusy] = useState(true); const [online, setOnline] = useState(() => navigator.onLine);
  const restricted = user.role === "student" || user.role === "parent";
  const load = async () => { setBusy(true); try { const [nextStudents, nextWorksheets, nextAttendance, nextExams, nextPayments] = await Promise.all([laravelApi.students(), laravelApi.worksheets(), laravelApi.attendance(), laravelApi.exams(), laravelApi.payments()]); setStudents(nextStudents); setWorksheets(nextWorksheets); setAttendance(nextAttendance); setExams(nextExams); setPayments(nextPayments); cacheDashboardSnapshot({ students: nextStudents, worksheets: nextWorksheets, attendance: nextAttendance, exams: nextExams, payments: nextPayments }); } catch (caught) { const snapshot = readDashboardSnapshot(); if (snapshot) { setStudents(snapshot.students as Student[]); setWorksheets(snapshot.worksheets as Worksheet[]); setAttendance(snapshot.attendance as Attendance[]); setExams(snapshot.exams as ExamResult[]); setPayments(snapshot.payments as Payment[]); toast("يتم عرض آخر بيانات محفوظة محلياً"); } else toast(caught instanceof ApiError ? caught.message : "تعذر تحميل البيانات"); } finally { setBusy(false); } };
  useEffect(() => { const handleOnline = () => { setOnline(true); void syncOfflineQueue().then(count => { if (count) toast(`تمت مزامنة ${count} عملية`); void load(); }); }; const handleOffline = () => setOnline(false); window.addEventListener("online", handleOnline); window.addEventListener("offline", handleOffline); void load(); return () => { window.removeEventListener("online", handleOnline); window.removeEventListener("offline", handleOffline); }; }, []);
  const currentStudent = user.student_account?.student || students[0];
  const ownAssignments = useMemo(() => worksheets.flatMap(item => item.assignments || []).filter(item => !currentStudent || item.student?.id === currentStudent.id), [worksheets, currentStudent]);
  return <div className="live-shell" dir="rtl"><MathUniverseBackground tone="system"/><aside className="live-sidebar"><div className="brand-block"><img src="/manus-storage/al-imtiaz-mark_99680b5d.png" alt="شعار الامتياز"/><div><strong>الامتياز</strong><span>في الرياضيات</span></div></div><div className="live-user"><span className="avatar">{user.name?.[0] || "م"}</span><div><b>{user.name}</b><small>{roleLabels[user.role]}</small></div></div><nav>{(restricted ? [{id:"overview",label:"ملخصي",icon:ShieldCheck}] : [{id:"overview",label:"نظرة عامة",icon:ShieldCheck},{id:"classes",label:"الصفوف",icon:GraduationCap},{id:"students",label:"الطلاب",icon:Users},{id:"attendance",label:"الحضور",icon:CalendarCheck},{id:"qr",label:"مسح QR",icon:Target},{id:"exams",label:"الامتحانات",icon:ClipboardList},{id:"worksheets",label:"الشيتات",icon:FileText},{id:"reports",label:"التقارير",icon:BarChart3},{id:"plugins",label:"متجر الإضافات",icon:Package}, {id:"settings",label:"الإعدادات",icon:Settings}]).map(item => { const Icon=item.icon; return <button key={item.id} className={tab===item.id?"live-nav active":"live-nav"} onClick={() => setTab(item.id as Tab)}><Icon size={18}/>{item.label}</button>; })}</nav><button className="live-logout" onClick={onLogout}><LogOut size={17}/> تسجيل الخروج</button></aside><main className="live-main"><header className="live-topbar"><div><span className="eyebrow">{roleLabels[user.role]}</span><h1>{restricted ? `لوحتك التعليمية، ${user.name}` : "لوحة الإدارة التعليمية"}</h1></div><div className={`sync-badge ${online ? "online" : "offline"}`}>{online ? "متصل" : "غير متصل — بيانات محفوظة"}</div><button className="outline" onClick={load}><RefreshCw size={15}/> تحديث البيانات</button></header>{busy ? <div className="live-loading"><RefreshCw className="spin"/> جارٍ تحميل البيانات...</div> : restricted ? <LearnerDashboard user={user} student={currentStudent} assignments={ownAssignments} attendance={attendance} exams={exams} payments={payments}/> : <AdminView tab={tab} students={students} attendance={attendance} exams={exams} payments={payments} worksheets={worksheets} onRefresh={load}/>}</main></div>;
}

function LearnerDashboard({ user, student, assignments, attendance, exams, payments }: { user: Awaited<ReturnType<typeof laravelApi.me>>; student?: Student; assignments: any[]; attendance: Attendance[]; exams: ExamResult[]; payments: Payment[] }) { const present = attendance.filter(item => item.status === "present").length; return <section className="live-page"><StudentQrCard student={student}/><div className="live-hero"><div><span className="eyebrow">{user.role === "parent" ? "بوابة ولي الأمر" : "بوابة الطالب"}</span><h2>{student?.name || user.name}</h2><p>{student ? `${student.grade} · ${student.group}` : "لا يوجد ملف طالب مرتبط بعد"}</p></div><BookOpen size={48}/></div><div className="live-stats"><Stat icon={<CalendarCheck/>} label="الحضور" value={`${present}/${attendance.length || 0}`}/><Stat icon={<ClipboardList/>} label="الامتحانات" value={`${exams.length}`}/><Stat icon={<CreditCard/>} label="المدفوعات" value={`${payments.filter(item => item.status === "paid").length}`}/><Stat icon={<FileText/>} label="الشيتات" value={`${assignments.length}`}/></div><div className="live-grid"><div className="card"><div className="card-head"><h3>آخر النتائج</h3><ClipboardList size={18}/></div>{exams.slice(0,4).map(item => <div className="live-row" key={item.id}><span>{item.title}</span><b>{item.score}/{item.max_score}</b></div>)}</div><div className="card"><div className="card-head"><h3>حالة الاشتراكات</h3><CreditCard size={18}/></div>{payments.slice(0,4).map(item => <div className="live-row" key={item.id}><span>{item.due_at}</span><b className={`payment-${item.status}`}>{item.status}</b></div>)}</div></div></section>; }

function StudentQrCard({ student }: { student?: Student }) {
  const [image, setImage] = useState("");
  useEffect(() => { if (!student?.id) return; laravelApi.studentQr(student.id).then(result => QRCode.toDataURL(result.payload, { width: 180, margin: 2, color: { dark: "#123e35", light: "#fffdf8" } })).then(setImage).catch(() => setImage("")); }, [student?.id]);
  if (!student) return null;
  return <div className="card student-qr-card"><div><span className="eyebrow">رمز الحضور الشخصي</span><h3>{student.name}</h3><p>اعرض هذا الرمز عند الوصول ليتم تسجيل حضورك تلقائياً مع التاريخ والوقت.</p></div>{image ? <img src={image} alt={`رمز حضور ${student.name}`}/> : <RefreshCw className="spin"/>}</div>;
}

function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="live-stat"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></div>; }
function AdminView({ tab, students, attendance, exams, payments, worksheets, onRefresh }: { tab: Tab; students: Student[]; attendance: Attendance[]; exams: ExamResult[]; payments: Payment[]; worksheets: Worksheet[]; onRefresh: () => Promise<void> }) {
  if (tab === "classes") return <ClassNavigator students={students} />;
  if (tab === "students") return <StudentDirectory students={students} attendance={attendance} exams={exams} payments={payments} worksheets={worksheets} onRefresh={onRefresh} />;
  if (tab === "reports") return <ReportsView students={students} attendance={attendance} exams={exams} payments={payments} />;
  if (tab === "plugins") return <PluginStorePanel onRefresh={onRefresh} />;
  if (tab === "settings") return <SettingsView />;
  if (tab === "attendance") return <CrudPanel title="إدارة الحضور" icon={<CalendarCheck/>} rows={attendance} fields={["student_id","date_at","status","note"]} onRefresh={onRefresh} create={laravelApi.createAttendance} update={laravelApi.updateAttendance} remove={laravelApi.deleteAttendance}/>;
  if (tab === "qr") return <section className="live-page"><QrAttendancePanel students={students} onRefresh={onRefresh}/></section>;
  if (tab === "exams") return <CrudPanel title="نتائج الامتحانات" icon={<ClipboardList/>} rows={exams} fields={["student_id","title","score","max_score","taken_at"]} onRefresh={onRefresh} create={laravelApi.createExam} update={laravelApi.updateExam} remove={laravelApi.deleteExam}/>;
  if (tab === "payments") return <CrudPanel title="الاشتراكات والمدفوعات" icon={<CreditCard/>} rows={payments} fields={["student_id","amount","status","due_at"]} onRefresh={onRefresh} create={laravelApi.createPayment} update={laravelApi.updatePayment} remove={laravelApi.deletePayment}/>;
  return <OverviewDashboard students={students} attendance={attendance} exams={exams} payments={payments} worksheets={worksheets}/>;
}

function ClassNavigator({ students }: { students: Student[] }) {
  const [stage, setStage] = useState<string | null>(null);
  const [grade, setGrade] = useState<string | null>(null);
  const [group, setGroup] = useState<string | null>(null);
  const stages = [{ name: "المرحلة الإعدادية", grades: ["أولى إعدادى", "ثانية إعدادى", "ثالثة إعدادى"] }, { name: "المرحلة الثانوية", grades: ["أولى ثانوى", "ثانية ثانوى", "ثالثة ثانوى رياضيات", "ثالثة ثانوى إحصاء"] }];
  const filtered = students.filter(item => item.grade === grade && item.group === group);
  const resetTo = (level: "stage" | "grade" | "group") => { if (level === "stage") { setStage(null); setGrade(null); setGroup(null); } if (level === "grade") { setGrade(null); setGroup(null); } if (level === "group") setGroup(null); };
  return <section className="live-page"><div className="page-head"><div><span className="eyebrow">التنظيم الأكاديمي</span><h2>الصفوف والمجموعات</h2></div>{stage && <button className="outline" onClick={() => resetTo(grade ? "grade" : "stage")}><ChevronLeft size={15}/> رجوع</button>}</div>{!stage && <div className="workflow-grid">{stages.map(item => <button className="workflow-card" key={item.name} onClick={() => setStage(item.name)}><GraduationCap size={26}/><strong>{item.name}</strong><small>{item.grades.length} صفوف</small></button>)}</div>}{stage && !grade && <div className="workflow-grid">{stages.find(item => item.name === stage)?.grades.map(item => <button className="workflow-card" key={item} onClick={() => setGrade(item)}><BookOpen size={24}/><strong>{item}</strong><small>عرض المجموعات</small></button>)}</div>}{stage && grade && !group && <div className="workflow-grid">{["بنين", "بنات"].map(item => <button className="workflow-card" key={item} onClick={() => setGroup(item)}><Users size={24}/><strong>{item}</strong><small>{students.filter(student => student.grade === grade && student.group === item).length} طالب</small></button>)}</div>}{group && <div className="card class-results"><div className="card-head"><div><span className="eyebrow">{stage} · {grade} · {group}</span><h3>إجمالي عدد الطلاب: {filtered.length}</h3></div><Users size={20}/></div>{filtered.map(student => <div className="live-row" key={student.id}><span>{student.name}</span><b>{student.status === "excellent" ? "ممتاز" : student.status === "average" ? "متوسط" : "ضعيف"}</b></div>)}</div>}</section>;
}

function StudentDirectory({ students, attendance, exams, payments, worksheets, onRefresh }: { students: Student[]; attendance: Attendance[]; exams: ExamResult[]; payments: Payment[]; worksheets: Worksheet[]; onRefresh: () => Promise<void> }) {
  const [search, setSearch] = useState(""); const [group, setGroup] = useState("الكل"); const [selected, setSelected] = useState<Student | null>(null); const [editing, setEditing] = useState<Student | null>(null); const [adding, setAdding] = useState(false);
  const filtered = students.filter(student => student.name.includes(search) && (group === "الكل" || student.group === group));
  const remove = async (student: Student) => { if (!window.confirm(`حذف الطالب ${student.name}؟`)) return; try { await laravelApi.deleteStudent(student.id); setSelected(null); await onRefresh(); toast("تم حذف الطالب"); } catch (caught) { toast(caught instanceof ApiError ? caught.message : "تعذر حذف الطالب"); } };
  return <section className="live-page"><div className="page-head"><div><span className="eyebrow">إدارة ملفات الطلاب</span><h2>الطلاب</h2></div><span className="live-count">إجمالي عدد الطلاب: {students.length}</span></div><div className="student-tools card"><label><Search size={15}/> بحث<input value={search} onChange={e => setSearch(e.target.value)} placeholder="ابحث باسم الطالب"/></label><label>المجموعة<select value={group} onChange={e => setGroup(e.target.value)}><option>الكل</option><option>بنين</option><option>بنات</option></select></label><button className="primary" onClick={() => { setAdding(true); setEditing(null); }}>إضافة طالب</button></div><div className="student-grid">{filtered.map(student => <button className="student-tile" key={student.id} onClick={() => setSelected(student)}><span className="avatar"><UserRound size={17}/></span><div><strong>{student.name}</strong><small>{student.grade} · {student.group}</small></div><ChevronLeft size={15}/></button>)}</div>{selected && <StudentCard student={selected} attendance={attendance} exams={exams} payments={payments} worksheets={worksheets} onClose={() => setSelected(null)} onEdit={() => { setEditing(selected); setSelected(null); }} onDelete={() => void remove(selected)}/>} {(adding || editing) && <StudentEditor initial={editing} onClose={() => { setAdding(false); setEditing(null); }} onSaved={async () => { setAdding(false); setEditing(null); await onRefresh(); }} />}</section>;
}

function StudentCard({ student, attendance, exams, payments, worksheets, onClose, onEdit, onDelete }: { student: Student; attendance: Attendance[]; exams: ExamResult[]; payments: Payment[]; worksheets: Worksheet[]; onClose: () => void; onEdit: () => void; onDelete: () => void }) {
  const ownAttendance = attendance.filter(item => item.student_id === student.id); const ownExams = exams.filter(item => item.student_id === student.id).sort((a, b) => b.taken_at.localeCompare(a.taken_at)); const ownPayments = payments.filter(item => item.student_id === student.id); const ownAssignments = worksheets.flatMap(item => item.assignments || []).filter(item => item.student?.id === student.id);
  return <div className="student-card-overlay"><article className="card student-card" dir="rtl"><div className="card-head"><div><span className="eyebrow">بطاقة الطالب</span><h2>{student.name}</h2></div><button className="icon-button" onClick={onClose} aria-label="إغلاق"><X size={18}/></button></div><div className="student-meta"><span>رقم الهاتف: {student.phone}</span><span>رقم ولي الأمر: {student.parent_phone || "—"}</span><span>الصف: {student.grade}</span><span>المجموعة: {student.group}</span></div><div className="student-stat-grid"><Stat label="الحضور" value={`${ownAttendance.filter(item => item.status === "present").length}`} icon={<CalendarCheck/>}/><Stat label="الغياب" value={`${ownAttendance.filter(item => item.status === "absent").length}`} icon={<CalendarCheck/>}/><Stat label="التأخير" value={`${ownAttendance.filter(item => item.status === "late").length}`} icon={<CalendarCheck/>}/><Stat label="الحالة" value={statusLabels[student.status]} icon={<ShieldCheck/>}/><Stat label="الاشتراك" value={ownPayments.some(item => item.status === "paid") ? "دفع" : "لم يدفع"} icon={<CreditCard/>}/></div><div className="live-grid"><div className="card"><h3>آخر امتحان</h3><p>{ownExams[0] ? `${ownExams[0].title}: ${ownExams[0].score}/${ownExams[0].max_score}` : "لا توجد نتيجة بعد"}</p></div><div className="card"><h3>آخر شيت</h3><p>{ownAssignments[0]?.worksheet?.title || "لا يوجد تكليف بعد"}</p></div></div><div className="student-actions"><button className="primary" onClick={onEdit}>تعديل</button><button className="outline danger-text" onClick={onDelete}>حذف الطالب</button></div></article></div>;
}

function StudentEditor({ initial, onClose, onSaved }: { initial: Student | null; onClose: () => void; onSaved: () => Promise<void> }) { const [form, setForm] = useState({ name: initial?.name || "", phone: initial?.phone || "", parent_phone: initial?.parent_phone || "", grade: initial?.grade || "أولى إعدادى", group: initial?.group || "بنين", status: initial?.status || "average" }); const [busy, setBusy] = useState(false); const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { if (initial) await laravelApi.updateStudent(initial.id, form); else await laravelApi.createStudent(form); toast(initial ? "تم تعديل بيانات الطالب" : "تمت إضافة الطالب"); await onSaved(); } catch (caught) { toast(caught instanceof ApiError ? caught.message : "تعذر حفظ بيانات الطالب"); } finally { setBusy(false); } }; return <div className="student-card-overlay"><form className="card student-editor" onSubmit={save}><div className="card-head"><h3>{initial ? "تعديل الطالب" : "إضافة طالب"}</h3><button type="button" className="icon-button" onClick={onClose}><X size={18}/></button></div>{([ ["name", "اسم الطالب"], ["phone", "رقم الهاتف"], ["parent_phone", "رقم ولي الأمر"] ] as const).map(([key, label]) => <label key={key}>{label}<input required={key !== "parent_phone"} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })}/></label>)}<label>الصف<select value={form.grade} onChange={e => setForm({ ...form, grade: e.target.value })}>{["أولى إعدادى", "ثانية إعدادى", "ثالثة إعدادى", "أولى ثانوى", "ثانية ثانوى", "ثالثة ثانوى رياضيات", "ثالثة ثانوى إحصاء"].map(value => <option key={value}>{value}</option>)}</select></label><label>المجموعة<select value={form.group} onChange={e => setForm({ ...form, group: e.target.value })}><option>بنين</option><option>بنات</option></select></label><label>حالة الطالب<select value={form.status} onChange={e => setForm({ ...form, status: e.target.value as typeof form.status })}><option value="excellent">ممتاز</option><option value="average">متوسط</option><option value="weak">ضعيف</option></select></label><button className="primary" disabled={busy}>{busy ? "جارٍ الحفظ..." : "حفظ"}</button></form></div>; }

function ReportsView({ students, attendance, exams, payments }: { students: Student[]; attendance: Attendance[]; exams: ExamResult[]; payments: Payment[] }) { return <section className="live-page"><div className="page-head"><div><span className="eyebrow">التقارير</span><h2>ملخص الأداء والاشتراكات</h2></div><BarChart3 size={24}/></div><div className="live-stats"><Stat label="إجمالي الطلاب" value={`${students.length}`} icon={<Users/>}/><Stat label="حضور" value={`${attendance.filter(item => item.status === "present").length}`} icon={<CalendarCheck/>}/><Stat label="متوسط الدرجات" value={exams.length ? `${Math.round(exams.reduce((sum, item) => sum + (item.score / item.max_score) * 100, 0) / exams.length)}%` : "—"} icon={<ClipboardList/>}/><Stat label="مدفوع" value={`${payments.filter(item => item.status === "paid").length}`} icon={<CreditCard/>}/></div></section>; }
function SettingsView() { return <section className="live-page"><div className="page-head"><div><span className="eyebrow">الإعدادات</span><h2>إعدادات المركز</h2></div><Settings size={24}/></div><div className="card settings-card"><h3>الأستاذ / أحمد عاطف الشافعى</h3><p>الامتياز في الرياضيات · إدارة الحساب والصلاحيات والمزامنة</p><div className="live-row"><span>حالة النظام</span><b className="payment-paid">متصل</b></div><div className="live-row"><span>المزامنة</span><b>تلقائية عند عودة الاتصال</b></div></div></section>; }

function LiveQrScanner({ onScan }: { onScan: (payload: string) => Promise<void> }) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const scannerRef = useRef<QrScanner | null>(null);
  const onScanRef = useRef(onScan);
  const lockedRef = useRef(false);
  const [state, setState] = useState<"idle" | "starting" | "active" | "error">("idle");
  const [error, setError] = useState("");
  onScanRef.current = onScan;
  const stop = () => { scannerRef.current?.destroy(); scannerRef.current = null; lockedRef.current = false; setState("idle"); };
  const start = async () => {
    if (!videoRef.current || scannerRef.current) return;
    setState("starting"); setError("");
    try {
      if (!(await QrScanner.hasCamera())) throw new Error("لم يتم العثور على كاميرا متاحة");
      const scanner = new QrScanner(videoRef.current, async result => {
        if (lockedRef.current) return;
        lockedRef.current = true;
        try { await onScanRef.current(result.data); } finally { window.setTimeout(() => { lockedRef.current = false; }, 1200); }
      }, { preferredCamera: "environment", maxScansPerSecond: 5, highlightScanRegion: true, highlightCodeOutline: true, returnDetailedScanResult: true, onDecodeError: decodeError => { if (decodeError !== QrScanner.NO_QR_CODE_FOUND) setError("تعذر قراءة الصورة من الكاميرا"); } });
      scannerRef.current = scanner;
      await scanner.start();
      setState("active");
    } catch (caught) {
      scannerRef.current?.destroy(); scannerRef.current = null; setState("error"); setError(caught instanceof Error ? caught.message : "تعذر تشغيل الكاميرا. تحقق من إذن الكاميرا أو استخدم الإدخال اليدوي.");
    }
  };
  useEffect(() => () => { scannerRef.current?.destroy(); scannerRef.current = null; }, []);
  return <div className="camera-scanner"><div className="camera-head"><div><b>المسح بالكاميرا</b><small>اسمح للكاميرا ثم وجّهها إلى QR الطالب</small></div><span className={`camera-status ${state}`}>{state === "active" ? "مباشر" : state === "starting" ? "جارٍ التشغيل" : state === "error" ? "يحتاج مراجعة" : "متوقف"}</span></div><div className="camera-frame"><video ref={videoRef} muted playsInline/></div><div className="camera-actions">{state === "active" ? <button type="button" className="outline" onClick={stop}>إيقاف الكاميرا</button> : <button type="button" className="primary" onClick={() => void start()} disabled={state === "starting"}>{state === "starting" ? "جارٍ طلب الإذن..." : "تشغيل الكاميرا"}</button>}<small>يمكنك استخدام قارئ USB أو الإدخال اليدوي أدناه كبديل.</small></div>{error && <p className="qr-result camera-error">{error}</p>}</div>;
}

function QrAttendancePanel({ students, onRefresh }: { students: Student[]; onRefresh: () => Promise<void> }) {
  const [selectedStudentId, setSelectedStudentId] = useState("");
  const [qrImage, setQrImage] = useState("");
  const [scanPayload, setScanPayload] = useState("");
  const [scanMessage, setScanMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const generate = async () => { if (!selectedStudentId) return toast("اختر طالباً أولاً"); setBusy(true); try { const result = await laravelApi.studentQr(Number(selectedStudentId)); setQrImage(await QRCode.toDataURL(result.payload, { width: 240, margin: 2, color: { dark: "#123e35", light: "#fffdf8" } })); } catch (caught) { toast(caught instanceof ApiError ? caught.message : "تعذر توليد QR"); } finally { setBusy(false); } };
  const submitPayload = async (payload: string) => { if (!payload.trim()) return; setBusy(true); setScanMessage(""); try { const result = await laravelApi.scanAttendance(payload.trim()); setScanMessage(result.already_recorded ? `تم تسجيل حضور ${result.attendance.student?.name || "الطالب"} مسبقاً اليوم.` : `تم تسجيل حضور ${result.attendance.student?.name || "الطالب"} في ${new Date(result.attendance.date_at).toLocaleTimeString("ar-EG")}.`); setScanPayload(""); await onRefresh(); } catch (caught) { setScanMessage(caught instanceof ApiError ? caught.message : "تعذر قراءة QR"); } finally { setBusy(false); } };
  const scan = async (event: React.FormEvent) => { event.preventDefault(); await submitPayload(scanPayload); };
  return <div className="card qr-panel"><div className="card-head"><div><span className="eyebrow">حضور ذكي</span><h3>بطاقة الطالب ومسح الحضور</h3></div><ShieldCheck size={19}/></div><div className="qr-layout"><div className="qr-generator"><label>عرض QR الطالب<select value={selectedStudentId} onChange={e => setSelectedStudentId(e.target.value)}><option value="">اختر طالباً</option>{students.map(student => <option key={student.id} value={student.id}>{student.name} — {student.grade}</option>)}</select></label><button className="primary" onClick={generate} disabled={busy}>توليد بطاقة QR</button>{qrImage && <div className="qr-preview"><img src={qrImage} alt="رمز حضور الطالب"/><small>يعرض الطالب هذا الرمز عند الحضور</small></div>}</div><div className="qr-scanner"><LiveQrScanner onScan={submitPayload}/><form onSubmit={scan}><label>الإدخال اليدوي أو قارئ USB<input value={scanPayload} onChange={e => setScanPayload(e.target.value)} placeholder="ألصق الرمز هنا أو استخدم قارئاً"/></label><button className="primary" disabled={busy}>تسجيل الحضور الآن</button>{scanMessage && <p className="qr-result">{scanMessage}</p>}</form><small>يُحفظ التاريخ والوقت من الخادم، ويُمنع تكرار حضور الطالب في اليوم نفسه.</small></div></div></div>;
}

function CrudPanel<T extends { id: number }>({ title, icon, rows, fields, onRefresh, create, update, remove }: { title: string; icon: React.ReactNode; rows: T[]; fields: string[]; onRefresh: () => Promise<void>; create: (payload: any) => Promise<any>; update: (id: number, payload: any) => Promise<any>; remove: (id: number) => Promise<any> }) { const [form, setForm] = useState<Record<string,string>>({}); const [editing, setEditing] = useState<number | null>(null); const [saving, setSaving] = useState(false); const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const payload={...form, student_id: Number(form.student_id), score: form.score ? Number(form.score):undefined, max_score: form.max_score ? Number(form.max_score):undefined, amount: form.amount ? Number(form.amount):undefined }; if (editing) await update(editing,payload); else await create(payload); setForm({}); setEditing(null); await onRefresh(); toast("تم حفظ السجل"); } catch (caught) { toast(caught instanceof ApiError ? caught.message : "تعذر حفظ السجل"); } finally { setSaving(false); } }; return <section className="live-page"><div className="page-head"><div><span className="eyebrow">بيانات حية</span><h2>{title}</h2></div><span className="live-count">{rows.length} سجل</span></div><form className="card live-crud-form" onSubmit={save}>{fields.map(field => <label key={field}>{labelForField(field)}<input required={field !== "note"} value={form[field] || ""} onChange={e => setForm({...form,[field]:e.target.value})}/></label>)}<button className="primary" disabled={saving}>{editing ? "تحديث" : "إضافة"}</button>{editing && <button type="button" className="outline" onClick={() => { setEditing(null); setForm({}); }}>إلغاء</button>}</form><div className="card table-card"><table><thead><tr>{fields.map(field => <th key={field}>{labelForField(field)}</th>)}<th>إجراء</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}>{fields.map(field => <td key={field}>{formatFieldValue(field, (row as any)[field], row as any)}</td>)}<td><button className="text-button" onClick={() => { setEditing(row.id); setForm(Object.fromEntries(fields.map(field => [field,String((row as any)[field] ?? "")]))); }}>تعديل</button><button className="text-button danger-text" onClick={async () => { await remove(row.id); await onRefresh(); toast("تم حذف السجل"); }}>حذف</button></td></tr>)}</tbody></table></div></section>; }


function OverviewDashboard({ students, attendance, exams, payments, worksheets }: { students: Student[]; attendance: Attendance[]; exams: ExamResult[]; payments: Payment[]; worksheets: Worksheet[] }) {
  const present = attendance.filter(item => item.status === "present").length;
  const paid = payments.filter(item => item.status === "paid").length;
  const examAverage = exams.length ? Math.round(exams.reduce((sum, item) => sum + (Number(item.score) / Math.max(Number(item.max_score), 1)) * 100, 0) / exams.length) : 0;
  const attendanceDays = useMemo(() => {
    const grouped = new Map<string, number>();
    attendance.forEach(item => { const key = String(item.date_at || "").slice(0, 10); if (key) grouped.set(key, (grouped.get(key) || 0) + (item.status === "present" ? 1 : 0)); });
    return Array.from(grouped.entries()).sort(([a], [b]) => a.localeCompare(b)).slice(-7).map(([date, value]) => ({ label: new Intl.DateTimeFormat("ar-EG", { weekday: "short" }).format(new Date(date)), value }));
  }, [attendance]);
  const maxAttendance = Math.max(...attendanceDays.map(item => item.value), 1);
  const paidRatio = payments.length ? Math.round((paid / payments.length) * 100) : 0;
  const topExams = exams.slice(0, 5).map(item => ({ title: item.title, score: Math.round((Number(item.score) / Math.max(Number(item.max_score), 1)) * 100) }));
  return <section className="live-page overview-dashboard">
    <div className="overview-hero"><div><span className="eyebrow">لوحة المؤشرات</span><h2>صورة واضحة لاتخاذ القرار</h2><p>تابع الحضور، التحصيل، والاشتراكات من شاشة واحدة باستخدام البيانات الحية من Laravel.</p></div><div className="overview-hero-mark"><Activity size={28}/><span>بيانات حية</span></div></div>
    <div className="overview-kpis"><OverviewKpi icon={<Users/>} label="إجمالي الطلاب" value={students.length} tone="green"/><OverviewKpi icon={<CalendarCheck/>} label="نسبة الحضور" value={`${attendance.length ? Math.round((present / attendance.length) * 100) : 0}%`} tone="blue"/><OverviewKpi icon={<TrendingUp/>} label="متوسط الامتحانات" value={`${examAverage}%`} tone="gold"/><OverviewKpi icon={<CreditCard/>} label="مدفوعات مكتملة" value={`${paid}/${payments.length}`} tone="rose"/></div>
    <div className="overview-grid overview-grid--charts">
      <div className="card overview-card chart-card"><div className="card-head"><div><span className="eyebrow">آخر السجلات</span><h3>اتجاه الحضور</h3></div><BarChart3 size={20}/></div><div className="bar-chart" aria-label="رسم بياني للحضور"><div className="bar-chart__axis"><span>الطلاب الحاضرون</span><span>{Math.max(...attendanceDays.map(item => item.value), 0)}</span></div><div className="bar-chart__bars">{attendanceDays.length ? attendanceDays.map(item => <div className="bar-chart__item" key={item.label}><div className="bar-chart__track"><span style={{ height: `${Math.max((item.value / maxAttendance) * 100, 8)}%` }} title={`${item.value} حاضر`}/></div><small>{item.label}</small></div>) : <p className="muted">لا توجد سجلات حضور بعد.</p>}</div></div></div>
      <div className="card overview-card"><div className="card-head"><div><span className="eyebrow">التحصيل</span><h3>أداء الامتحانات</h3></div><Target size={20}/></div><div className="exam-bars">{topExams.length ? topExams.map(item => <div className="exam-bar" key={`${item.title}-${item.score}`}><div><span>{item.title}</span><b>{item.score}%</b></div><div className="exam-bar__track"><span style={{ width: `${item.score}%` }}/></div></div>) : <p className="muted">لا توجد نتائج امتحانات بعد.</p>}</div></div>
    </div>
    <div className="overview-grid overview-grid--lower"><div className="card overview-card payment-overview"><div className="card-head"><div><span className="eyebrow">الاشتراكات</span><h3>حالة المدفوعات</h3></div><PieChart size={20}/></div><div className="payment-ring" style={{ background: `conic-gradient(#16846d 0 ${paidRatio}%, #b87945 ${paidRatio}% 100%)` }}><div><strong>{paidRatio}%</strong><small>مكتمل</small></div></div><div className="payment-legend"><span><i className="legend-dot legend-dot--green"/>مدفوع {paid}</span><span><i className="legend-dot legend-dot--copper"/>معلّق {payments.length - paid}</span></div></div><div className="card overview-card learning-flow"><div className="card-head"><div><span className="eyebrow">مسار المتعلم</span><h3>من الحضور إلى الإتقان</h3></div><GraduationCap size={20}/></div><div className="flow-steps"><FlowStep number="١" label="حضور" icon={<CalendarCheck/>}/><ChevronLeft size={16}/><FlowStep number="٢" label="شيتات" icon={<FileText/>}/><ChevronLeft size={16}/><FlowStep number="٣" label="امتحان" icon={<ClipboardList/>}/><ChevronLeft size={16}/><FlowStep number="٤" label="إتقان" icon={<Target/>}/></div><p className="muted">تم تحميل {worksheets.length} شيتاً تعليمياً للمتابعة.</p></div></div>
  </section>;
}

function OverviewKpi({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string | number; tone: string }) { return <div className={`overview-kpi overview-kpi--${tone}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div><Activity size={16}/></div>; }
function FlowStep({ number, label, icon }: { number: string; label: string; icon: React.ReactNode }) { return <div className="flow-step"><span>{icon}</span><b>{number}</b><small>{label}</small></div>; }
